apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-recognition-microservice
  labels:
    app: face-recognition-microservice
spec:
  selector:
    matchLabels:
      app: face-recognition-microservice
  template:
    metadata:
      labels:
        app: face-recognition-microservice
    spec:
      containers:
        - name:  face-recognition-microservice
          image:  face-recognition-microservice
          imagePullPolicy: Never
          env:
            - name:  DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: faces-database
                  optional: false

            - name:  THRESHOLD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: threshold
                  optional: true

          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1"
              memory: "2G"
      restartPolicy: Always
            