apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-info-microservice
  labels:
    app: person-info-microservice
spec:
  selector:
    matchLabels:
      app: person-info-microservice
  template:
    metadata:
      labels:
        app: person-info-microservice
    spec:
      containers:
        - name:  person-info-microservice
          image:  person-info-microservice
          imagePullPolicy: Never
          env:
            - name:  DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: persons-database
                  optional: false

          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1"
              memory: "1G"
      restartPolicy: Always
            